name: "Suggest a new feature or improvement 🚀"
description: Suggest a new feature or improvement (this does not mean you have to implement
  it)
labels:
- Issue-Feature
body:
- id: description
  type: textarea
  attributes: 
    label: Suggested new feature or improvement
    placeholder: Tell us about the new feature or improvement you'd like to see.
  validations:
    required: true
    
- id: scenario
  type: textarea
  attributes:
    label: Scenario
    placeholder: How could this new feature be used? Feel free to provide examples.
  validations:
    required: true

- id: supportinginfo
  type: textarea
  attributes:
    label: Additional details
    placeholder: Enter more info or links to give us more details. 
  validations:
    required: false

- type: markdown
  attributes:
    value: Please limit one request per issue.