name: "Report a translation problem 🌐"
description: Report incorrect translations
labels:
- Issue-Translation

body:
- type: markdown
  attributes:
    value: Please make sure to [search for existing issues](https://github.com/microsoft/devhomegithubextension/issues) before filing a new one!

- id: devhomeversion
  type: input
  attributes:
    label: Dev Home version
    placeholder: "0.1.3651.0"
    description: 
  validations:
    required: false

- id: githubextensionversion
  type: input
  attributes:
    label: GitHub Extension (for Dev Home) version
    placeholder: "0.1.3651.0"
    description: 
  validations:
    required: false

- id: languageaffected
  type: input
  attributes:
    label: 🌐 Language
    placeholder: "Example: German"
  validations:
    required: true

- type: textarea
  attributes: 
    label: ❌ Actual phrase(s)
    placeholder: What is there? Please include a screenshot - it's very helpful to us! 
  validations:
    required: true

- type: textarea
  attributes: 
    label: ✔️ Expected phrase(s)
    placeholder: What phrase was expected?
  validations:
    required: false

- type: textarea
  attributes:
    label: Why is the current translation wrong
    placeholder: Why do you feel this translation is incorrect?
  validations:
    required: true